version: '3'

services:
  discovery:
    image: openjdk:11
    working_dir: /app
    command: java -jar discovery-docker.jar
    ports:
      - "8761:8761"
    volumes:
      - ./discovery-server/target:/app
    networks:
      - bizmatch_network

  gateway:
    image: openjdk:11
    working_dir: /app
    command: java -jar api-gateway-service-0.0.1-SNAPSHOT.jar
    ports:
      - "9090:9090"
    volumes:
      - ./api-gateway-service/target:/app
    networks:
      - bizmatch_network

  auth:
    image: openjdk:11
    working_dir: /app
    command: java -jar authentification-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8082:8082"
    volumes:
      - ./authentification-service/target:/app
    networks:
      - bizmatch_network

  besoin:
    image: openjdk:11
    working_dir: /app
    command: java -jar besoins-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8099:8099"
    volumes:
      - ./besoins-service/target:/app
    networks:
      - bizmatch_network

  business:
    image: openjdk:11
    working_dir: /app
    command: java -jar business-server-0.0.1-SNAPSHOT.jar
    ports:
      - "8111:8111"
    volumes:
      - ./business-server/target:/app
    networks:
      - bizmatch_network

  crm:
    image: openjdk:11
    working_dir: /app
    command: java -jar CRM-0.0.1-SNAPSHOT.jar
    ports:
      - "8091:8091"
    volumes:
      - ./CRM/target:/app
    networks:
      - bizmatch_network

  event:
    image: openjdk:11
    working_dir: /app
    command: java -jar event-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8084:8084"
    volumes:
      - ./event-service/target:/app
    networks:
      - bizmatch_network

  marche:
    image: openjdk:11
    working_dir: /app
    command: java -jar gestionMarche-0.0.1-SNAPSHOT.jar
    ports:
      - "8090:8090"
    volumes:
      - ./gestionMarche/target:/app
    networks:
      - bizmatch_network

  prestation:
    image: openjdk:11
    working_dir: /app
    command: java -jar PrestationServices-0.0.1-SNAPSHOT.jar
    ports:
      - "9093:9093"
    volumes:
      - ./PrestationServices/target:/app
    networks:
      - bizmatch_network

  relation:
    image: openjdk:11
    working_dir: /app
    command: java -jar Relations-1.0-SNAPSHOT.jar
    ports:
      - "9091:9091"
    volumes:
      - ./Relations/target:/app
    networks:
      - bizmatch_network

  reunion:
    image: openjdk:11
    working_dir: /app
    command: java -jar reunion-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8083:8083"
    volumes:
      - ./reunion-service/target:/app
    networks:
      - bizmatch_network

  user:
    image: openjdk:11
    working_dir: /app
    command: java -jar user-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8081"
    volumes:
      - ./user-service/target:/app
    networks:
      - bizmatch_network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BizmatchFinal
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - bizmatch_network

networks:
  bizmatch_network:
    external: true
